from __future__ import annotations

from typing import Any, Protocol


class StreamingRepositoryFactory(Protocol):
    def moderation(self) -> Any: ...

    def candidates(self, max_pool_size: int) -> Any: ...

    def rankings(self) -> Any: ...

    def selections(self) -> Any: ...

    def response_activities(self) -> Any: ...

    def response_history(self) -> Any: ...

    def ranking_history(self, history_size: int) -> Any: ...
