"""Deprecated compatibility import. Use app.shared.contracts.plugins.registration."""

from app.shared.contracts.plugins.registration import (
    ActivityProvider,
    CapabilityPolicy,
    CapabilityRegistration,
    CapabilityUnavailable,
    CommandHandler,
    CommandRejected,
    DuplicateCapability,
    EventSubscription,
    PluginActivityRequest,
    PluginActivitySpec,
    PluginContractError,
    PluginDependencyMissing,
    PluginDescriptor,
    PluginEventSubscriber,
    PluginHealth,
    PluginHealthStatus,
    PluginLifecycle,
    PluginRegistration,
    PluginStartFailed,
    PluginStopFailed,
    PluginUnavailable,
    QueryFailed,
    QueryHandler,
)

__all__ = [
    "ActivityProvider",
    "CapabilityPolicy",
    "CapabilityRegistration",
    "CapabilityUnavailable",
    "CommandHandler",
    "CommandRejected",
    "DuplicateCapability",
    "EventSubscription",
    "PluginActivityRequest",
    "PluginActivitySpec",
    "PluginContractError",
    "PluginDependencyMissing",
    "PluginDescriptor",
    "PluginEventSubscriber",
    "PluginHealth",
    "PluginHealthStatus",
    "PluginLifecycle",
    "PluginRegistration",
    "PluginStartFailed",
    "PluginStopFailed",
    "PluginUnavailable",
    "QueryFailed",
    "QueryHandler",
]
