from __future__ import annotations

from collections.abc import Callable
from typing import Protocol

from app.domain.streaming import (
    HealthCheckItem,
    ObsPreparationSnapshot,
    RunOfShowSummary,
    StreamPreparationResult,
    StreamSession,
    YouTubeAuthenticationState,
    YouTubeBroadcastSummary,
    YouTubeLiveChatSnapshot,
    YouTubeStreamSnapshot,
)


class YouTubePreparationPort(Protocol):
    @property
    def adapter_type(self) -> str: ...

    async def get_authentication_state(self) -> YouTubeAuthenticationState: ...

    async def authenticate(self) -> YouTubeAuthenticationState: ...

    async def list_broadcasts(self) -> tuple[YouTubeBroadcastSummary, ...]: ...

    async def check_authentication(self) -> bool: ...

    async def resolve_broadcast(self, broadcast_id: str) -> YouTubeBroadcastSummary: ...

    async def resolve_bound_stream(self, broadcast_id: str) -> YouTubeStreamSnapshot: ...

    async def get_stream_status(self, stream_id: str) -> str: ...

    async def get_broadcast_status(self, broadcast_id: str) -> str: ...

    async def get_live_chat_id(self, broadcast_id: str) -> str | None: ...

    async def get_live_chat_availability(self, broadcast_id: str) -> YouTubeLiveChatSnapshot: ...

    async def health_check(self) -> bool: ...


class ObsPreparationPort(Protocol):
    async def connect(self) -> None: ...

    async def health_check(self) -> bool: ...

    async def get_output_status(self) -> str: ...

    async def get_current_scene(self) -> str: ...

    async def get_current_scene_collection(self) -> str: ...

    async def get_audio_source_states(self) -> dict[str, bool]: ...

    async def get_avatar_source_visibility(self) -> bool: ...

    async def snapshot(self) -> ObsPreparationSnapshot: ...


class TtsHealthPort(Protocol):
    async def check(self, *, required: bool) -> HealthCheckItem: ...


class AvatarHealthPort(Protocol):
    async def check(self, *, required: bool) -> HealthCheckItem: ...


class RunOfShowRepository(Protocol):
    def list_available(self) -> tuple[RunOfShowSummary, ...]: ...

    def load(self, run_of_show_id: str) -> RunOfShowSummary: ...

    def validate(self, run_of_show_id: str) -> RunOfShowSummary: ...


class StreamSessionRepository(Protocol):
    def create(self, session: StreamSession) -> StreamSession: ...

    def get(self, session_id: str) -> StreamSession | None: ...

    def save(self, session: StreamSession) -> StreamSession: ...

    def find_active_or_preparing(self) -> StreamSession | None: ...


PreparationSubscriber = Callable[[StreamPreparationResult], None]


class StreamPreparationPublisher(Protocol):
    def publish(self, result: StreamPreparationResult) -> None: ...

    def subscribe(self, subscriber: PreparationSubscriber) -> Callable[[], None]: ...
