from __future__ import annotations

from typing import Protocol


class ObsStreamingControlPort(Protocol):
    @property
    def adapter_type(self) -> str: ...

    async def start_stream(self) -> None: ...

    async def stop_stream(self) -> None: ...

    async def get_output_status(self) -> str: ...

    async def get_connection_status(self) -> str: ...

    async def disconnect(self) -> None: ...


class YouTubeStreamingControlPort(Protocol):
    @property
    def adapter_type(self) -> str: ...

    async def get_stream_status(self, stream_id: str) -> str: ...

    async def transition_broadcast_to_live(self, broadcast_id: str) -> None: ...

    async def transition_broadcast_to_complete(self, broadcast_id: str) -> None: ...

    async def get_broadcast_status(self, broadcast_id: str) -> str: ...
